### ISSUE TITLE
删除空格所导致的窗口寻找bug

### ISSUE THREAD

**Issue by Mike-Sagiri** [svr2kos2/TaskmgrPlayer#2]
在修改config的参数的时候发现，如果修改的窗口的标题栏的窗口名称含有空格，如：**无标题 - 记事本**，在实际执行后会发现寻找窗口失败，此时反馈的所要找寻的窗口会自动删除空格如：**无标题-记事本**。  
***  
查看了源代码后，发现第一个删除所有空格的函数似乎是此bug的根源。请问作者能否在后续的版本中修复？

**Comment by Mike-Sagiri** [comment]
另外，对于没有子窗口类的窗口该如何配置config呢

**Comment by svr2kos2** [comment]
> 在修改config的参数的时候发现，如果修改的窗口的标题栏的窗口名称含有空格，如：**无标题 - 记事本**，在实际执行后会发现寻找窗口失败，此时反馈的所要找寻的窗口会自动删除空格如：**无标题-记事本**。
> 
> 查看了源代码后，发现第一个删除所有空格的函数似乎是此bug的根源。请问作者能否在后续的版本中修复？

配置文件里我把字符串类型加了引号, 这样就可以包含空格了

**Comment by svr2kos2** [comment]
> 另外，对于没有子窗口类的窗口该如何配置config呢

填空之后会默认选择主窗口

**Comment by Mike-Sagiri** [comment]
**感谢帮助**
